import { GoogleGenAI, Type, Schema } from "@google/genai";
import { NextResponse } from "next/server";
import { adminDb } from "@/lib/firebase-admin";

export async function POST(request: Request) {
  try {
    const { profile, topic, learningStyle, interestReason } = await request.json();
    
    if (!profile || !topic) {
      return NextResponse.json({ error: "Faltan datos requeridos" }, { status: 400 });
    }

    const docSnapshot = await adminDb.collection("knowledge_base").doc(topic).get();
    if (!docSnapshot.exists) {
      return NextResponse.json({ error: "El documento seleccionado no existe en la base de datos" }, { status: 404 });
    }

    const baseContext = docSnapshot.data()?.content;
    const numSlides = 4; // Fijo a 4 para este piloto

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

    const responseSchema: Schema = {
      type: Type.ARRAY,
      description: "A list of learning slides.",
      items: {
        type: Type.OBJECT,
        properties: {
          title: {
            type: Type.STRING,
            description: "Short title for the slide",
          },
          content: {
            type: Type.STRING,
            description: "Educational content adapted to the user's profile and constraints.",
          },
          icon: {
            type: Type.STRING,
            description: "An emoji that visually represents the slide's content",
          },
        },
        required: ["title", "content", "icon"],
      },
    };

    const prompt = `
You are an expert instructional designer for the Mexican public administration (INAP).
Create exactly ${numSlides} learning slides based on the provided BASE CONTEXT document.

You must deeply customize the content based on these user variables:
1. Profile/Profession: "${profile}"
2. Learning Style: "${learningStyle}" 
   - If "Teórico", quote laws and articles.
   - If "Práctico", use real-world examples and problem-solving.
   - If "Ejecutivo", give bullet points and bottom-line impact.
3. Motivation: "${interestReason}" (Tie the examples to their specific motivation).

The content MUST BE IN SPANISH. Make it highly engaging.

BASE CONTEXT:
${baseContext}
`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: responseSchema,
        temperature: 0.2,
      },
    });

    const textOutput = response.text;
    if (!textOutput) {
      throw new Error("No output generated by Gemini");
    }

    const slides = JSON.parse(textOutput);
    return NextResponse.json({ slides });

  } catch (error: any) {
    console.error("Error generating slides:", error);
    return NextResponse.json({ error: error.message || "Failed to generate slides" }, { status: 500 });
  }
}
